### PR TITLE
Show failed attempt at defining set_of_sequences

### PR DESCRIPTION
**Pull request by Nielius**
*NOT TO BE MERGED*

This is just to show a failed attempt where I tried to do to convert Paul's `set_of_sequences` into something that uses the built-in `sig`. I'm not sure anymore that we should try to do that.

### CODE REVIEW

**Comment by paulcadman** [comment]
Thanks @Nielius for putting this together and for the useful commentary.

It'd be great if we could find a place in the repo for attempts at new ideas that don't work (yet).

**Comment by awalterschulze** [comment]
> Thanks @Nielius for putting this together and for the useful commentary.
> 
> It'd be great if we could find a place in the repo for attempts at new ideas that don't work (yet).

Isn't that what TODO: Help Wanted is for?
We just add an explanation in the comment.

**Comment by awalterschulze** [comment]
But I think a pull request in draft is also great.

**Comment by awalterschulze** [comment]
I think we learned a lot from this, but now might be a good time to close this pull request, what do you think?

**Comment by Nielius** [comment]
Yes, I agree.

**Pull request closed without merging**
