### PR TITLE
Documentation Improved

### PR DESCRIPTION
**Pull request by suraj0223**
Documentation improved in CONTRIBUTING.md

### CODE REVIEW

**Comment by awalterschulze** [comment]
I do think we need to keep the verbatim `(* TODO: Good First Issue *)` and `(* TODO: Help Wanted *)`.  This makes it very clear exactly how to insert a TODO, so that it is easily searchable.

Possible this means updating the headings to use colons instead of commas too.

I am concerned though that now it reads
"A proof may be left out if: HEADING bulletedlist with one item HEADING ..."
And I don't have a good idea of how to fix this.

And I have the very minor conern that now these are technically their own section instead of a subsection of TODO, Admitted ...

Could you tell me why you think this improves documentation?  Then we can try to fix the problem.

**Comment by suraj0223** [comment]
I think making a heading it is easier to found the topic. One Fix may possible that  make TODO a heading and (*Good first issue*) and (*Help Wanted*) to be subHeading

**Comment by suraj0223** [comment]
I think listing may help.

**Comment by awalterschulze** [comment]
Ah nice.  Yes listing is a great idea and TIL you can list headings.

I would opt for keeping the verbatim TODOs at the end of the sentences and now since they are under headings rewriting them starting with a capital letter.

```
A proof may be left out for two reasons.

 #### 1. Good First Issue
 - You are lazy, for example maybe you see the proof will be similar to other proofs (this gives beginners an opportunity to also contribute).  In this case please add `(* TODO: Good First Issue *)`.
 #### 2. Help Wanted
 - You need help (this gives beginners who are up for a challenge, a chance to contribute). In this case please add `(* TODO: Help Wanted *)`.
```

**Comment by awalterschulze** [comment]
Going to close, since there is no activity.
Please feel free to reopen in future.

**Pull request closed without merging**
