### PR TITLE
integrate inductive predicate proofs

### PR DESCRIPTION
**Pull request by aymanosman**
This makes the experiemental proofs use the now agreed upon definitions.

### CODE REVIEW

**Comment by paulcadman** [comment]
🥇

**Comment by awalterschulze** [comment]
This is exactly what I meant with my comment on the previous pull request.  So now all is fixed :)

Maybe these proofs could all move into matches_pred?
I mean it is still an experiment, but what in this repo isn't.

**Comment by aymanosman** [comment]
I was really happy to see that the proofs dealt robustly with the addition of cases to the inductive predicate, as we hoped.

The issue with the `not` case is a little troubling. 

I took a look at the Brzozowski implementation, I wonder if the `nor` constructor relates in any way to positivity checking.

**Comment by awalterschulze** [comment]
`nor` has the same problem with `not`.  I have tried using a `with` in the inductive predicate for Brzozowski's implementation as was done for even and odd here: http://www.cs.umd.edu/class/fall2019/cmsc631/res/IndPrinciples.html 
But I am not convinced yet that this solves the problem.

**Pull request merged**
