### PR TITLE
Renames seqs to lang (short for language)

### PR DESCRIPTION
**Pull request by paulcadman**
Several of us have been confused by the similarity of seq and seqs. In
the regex reexamined paper they call a set of sequences a language in
the context of regular expressions. This shortens to lang.

This is something that came up in the pairing yesterday. Can anyone else think
of a better name? Should we also rename `seq` to `string` or `str`?

NB: PDF have changed because of https://github.com/awalterschulze/regex-reexamined-coq/pull/114/files#diff-2a27707e33c328861511ef9552df2b51R15

### CODE REVIEW

**Comment by awalterschulze** [comment]
I like the `lang` idea.
We can also rename `seq` to `str` and update the paper to say `string` instead of `sequence`, but we can do that in a separate step.

I think the markdown has changed before, which resulted in the pdf changing, if you regenerate it.
But this commit doesn't contain the changes to the markdown, so maybe we can update the pdf in a separate commit.

**Comment by awalterschulze** [comment]
Haha I didn't read your second part of the description, seems we have the same idea about `str` :)

**Comment by awalterschulze** [comment]
We can marge this first https://github.com/awalterschulze/regex-reexamined-coq/pull/115
then yours can be a commit that only renames `seqs` to `lang`, because this doesn't need to modify the paper.
And then we can have a follow up that renames `seq` to `str`, including renaming `sequence` to `string` in the paper.
What do you think?

**Comment by paulcadman** [comment]
@awalterschulze - good idea let's do that, sorry I misunderstood why the PDF had changed.

**Comment by awalterschulze** [comment]
No I am sorry, I should have updated the pdf, when I changed the markdown, I was lazy.

**Comment by mheiber** [comment]
Thanks for doing this! I still feel like it was my fault for getting confused, but this new naming seems nice.

**Comment by awalterschulze** [comment]
We should also split renaming the file Sequences.v and renaming `seqs` in two separate commits.
Otherwise it will just look like a new file.

**Comment by awalterschulze** [comment]
@mheiber you were not the first.  You were simply the last, that pushed this over the line and made it obvious that it needed renaming.

**Comment by paulcadman** [comment]
@mheiber I was confused by this every time I came back to the repo. I also learned how to do find and replace efficiently in a project with counsel-rg and wgrep in emacs.

**Pull request merged**
