### PR TITLE
a folder for more things we want to have in the standard library

### PR DESCRIPTION
**Pull request by awalterschulze**
Please read the readme in the pull request before commenting.

Happy to bikeshed on the name, before we start moving things here.

Lets have some puns and please vote with some github emoji for the puns you like, so we can actually also settle on one. 

Note: You get unlimited votes.

### CODE REVIEW

**Comment by awalterschulze** [comment]
`nps` -> national proof service

**Comment by awalterschulze** [comment]
stdwish -> the standard library we wish to have or the std we wish to have

**Comment by awalterschulze** [comment]
Good to know we aren't the first to need this.

But Max, I don't think you are taking this review seriously.
I expect a pun :P

**Comment by awalterschulze** [comment]
coqney: since this is our accent?

**Comment by paulcadman** [comment]
`stockcoq` -> a store of coq goodies

**Comment by paulcadman** [comment]
`coq-a-doodle-doo` -> makes me smile

**Comment by paulcadman** [comment]
`coqorico` -> french for coq-a-doodle-doo

**Comment by awalterschulze** [comment]
> `coq-a-doodle-doo` -> makes me smile

I worry about importing this, but otherwise I love it.

**Comment by paulcadman** [comment]
`coqlude`

**Comment by awalterschulze** [comment]
> > `coq-a-doodle-doo` -> makes me smile
> 
> I worry about importing this, but otherwise I love it.

How about shortening it

`doodledo`

**Comment by Nielius** [comment]
concoqtions

**Comment by awalterschulze** [comment]
> > > `coq-a-doodle-doo` -> makes me smile
> > 
> > 
> > I worry about importing this, but otherwise I love it.
> 
> How about shortening it
> 
> `doodledo`

Maybe this is a good name for a monad library, when we get to that :)

**Comment by awalterschulze** [comment]
So far we have:
`coqlude`, which so far I just think is funny.
`coqney`, which Paul at least thinks is funny.
`stockcoq`, which I think is funny and appropriate
`doodledo`, for a future monad library
`concoqtions`, which I think is funny and appropriate

So for me it is between `stockcoq` and `concoqtions`.  If no one else votes, I am going to make a call, at latest tomorrow.  Happy to change it again later.

**Comment by awalterschulze** [comment]
`concoqtions` is the one I can't get out of my head, but `stockcoq` makes me think of chicken stock, which is a base for a "curry".

**Comment by awalterschulze** [comment]
So I am going to go with `coqstock`, until someone brings this up again.

**Pull request merged**
