### PR TITLE
use coq_makefile Fixes #35

### LINKED ISSUE #35: Use `coq_makefile` at some point
We can improve our Makefile by using `coq_makefile`. (Our current Makefile just recompiles everything every time.)

See <https://coq.inria.fr/refman/practical-tools/utilities.html#building-a-coq-project> for details.

### PR DESCRIPTION
**Pull request by aymanosman**
Something I'm not sure about is how to check that dependencies are up to date. Seems like a job for CI.

What I would like is a CI check that fails if rerunning `coq_makefile -f _CoqProject -o Makefile` changes anything.

### CODE REVIEW

**Comment by aymanosman** [comment]
`coqdep` is called to calculate module dependencies everytime, so that is not a worry. But it would still be nice to fail a check if the dependency change was not committed.

```
> make
COQDEP VFILES
COQC matches_pred.v
COQC inductive_predicate_experiment.v
```

**Comment by awalterschulze** [comment]
This is very cool. 

@paulcadman has setup github actions as our CI.  So maybe he can help?
But I don't think that should be a blocker in merging this, only another incremental improvement later. 

This only important thing is that we check that the CI is still calling the makefile to do actual checks of the proofs.

**Comment by awalterschulze** [comment]
Screenshot 2020-04-29 at 20 34 55
And this seems to be the case :)

**Comment by aymanosman** [comment]
Looks like the dependencies won't be a problem. They are generated everytime.

**Pull request merged**
