### PR TITLE
`matches' as an inductive predicate

### PR DESCRIPTION
**Pull request by aymanosman**
Here is my experiment with making `matches` into an inductive predicate.

I'm not sure whether this should actually be merged in its current state, a PR just makes it easier to discuss things.

Maybe we can take some lessons learned from this approach and apply them to our actual proofs.

### CODE REVIEW

**Comment by paulcadman** [comment]
This is very interesting ! thanks

**Comment by awalterschulze** [comment]
I have skimmed this, but will have a more proper look later.  Sorry for the delay.

**Comment by awalterschulze** [comment]
We just need to include a theorem like this to tie this work in with everything else.
```
Theorem x: forall (r: regex X) (xs: list X), 
  (* function *) matches r xs = true <-> (* inductive *) matches r xs
.
```
This is a super cool angle on solving these proofs, great job :D

**Comment by awalterschulze** [comment]
I think we can merge all these proofs into matches_pred.v
Thanks again for this.  It is really interesting.
I think I am just worried about the `not` case.

**Pull request merged**
