### PR TITLE
Walters attempt at reorder

### PR DESCRIPTION
**Pull request by awalterschulze**
I needed to do these proofs for myself as well, so I could learn from others.

Looking at the proofs done by @Nielius and @paulcadman was super helpful.
I couldn't have done it without your work.
The key for me was how @Nielius broke it up into Lemmas and @paulcadman broke `to_list_to_tree` up into even more into Lemmas.
Another thing was that the current to_tree function and even this "better" one, makes the proving harder than it should be.  This results in multiple levels of induction, where only one or two should be enough, but I guess it was good practice.

I have also added comments to explain my reasoning.

I am kind of wondering how @Nielius decided when to break something up into separate Lemmas, because this does not come naturally to me at all.

I think I figured out @paulcadman broke things up, to make sure that `simpl` only took on step.
I bypassed this with `Arguments <function name>: simpl nomatch.`, but I think @paulcadman 's is still more readable, since I needed comments to make mine clear.

### CODE REVIEW

**Comment by Nielius** [comment]
Nice work. I like the comments, especially since this repo is meant for learning anyway, and looking back at some of the things I did some time ago, I regret not leaving some insightful comments.

Re how I come up with which lemmas to take, I first proved the statements just mathematically, with pen and paper, and then there are usually some "key insights" that I turn into lemmas. For me it's actually quite similar to how when you're programming, you decide that something should be a function of its own.

**Comment by Nielius** [comment]
I'm also glad you found this `Arguments <function name>: simpl nomatch`. I'd been looking for something like that.

**Comment by awalterschulze** [comment]
Wow ok, so you first prove it on paper, that is very interesting.
I have some ways to go, for me Coq is a step in a way to one day learn how to prove things on paper.
Okay, but thinking of it like programming might help.

I kind of wish there was a `simpl` that one did one step at a time, so that I didn't have to this:
`Arguments <function name>: simpl nomatch`
But at least there is something.

**Comment by Nielius** [comment]
Yeah, exactly, I was also looking for a `simpl` that did only one step, but I tried lots of things and googled, but I get the impression that it just doesn't exist. (Happy to be proven wrong by anyone reading this.) There are things like `lazy` and `cbv` (call-by-value) that also allow you to specify what kind of conversions you want to do (alpha, beta, delta, ...), but I haven't managed to use them to do exactly what I want.

**Comment by awalterschulze** [comment]
Ah I think that doing manual `alpha, beta, delta, ...` with `lazy`, `cbv` or `cbn` or something is probably the right path to doing a single step correctly.  Great pointer.

**Comment by awalterschulze** [comment]
After looking at Section 2.4.2 Reduction Rules in Coq Art.
I tried some combinations of lazy, cbn, cbv and delta, beta, iota, zeta, but unfortunately none worked as good as Arguments or Lemmas :(

**Pull request merged**
